- alias: 'Notify VIPKID'
  trigger:
    # 定时提醒
    - platform: time
      at: '18:05:00'

    # 5分钟内提醒
    - platform: numeric_state
      entity_id: sensor.vipkid
      below: 300

    # 15分钟提醒
    - platform: numeric_state
      entity_id: sensor.vipkid
      below: 900

    # 1小时内提醒
    - platform: numeric_state
      entity_id: sensor.vipkid
      below: 3600

  condition:
    - condition: numeric_state
      entity_id: sensor.vipkid
      below: 43200

  action:
    - service: script.set_vlc_volume
      data:
        value: 0.6

    - service: tts.baidu_say
      data_template:
        entity_id: media_player.speaker_vlc
        message: >-
          {%- for num in range(0,2) -%}
            卢维斯，今天{{- strptime(states.sensor.vipkid.attributes.time, '%Y-%m-%d %X').strftime('%H') -}}点
            {{- strptime(states.sensor.vipkid.attributes.time, '%Y-%m-%d %X').strftime('%M') -}}分，将要开始和
            {{- states.sensor.vipkid.attributes.teacher -}} 老师的英文课！
            {%- if states('sensor.vipkid')|int <= 300 -%}
            赶快进教室准备上课吧！
            {%- endif -%}
          {% endfor -%}

    - delay: 00:00:05
    - wait_template: >-
        {{ not is_state('media_player.speaker_vlc', 'playing') }}

    # 恢复播放器的音量
    - service: script.set_volume_to_pre