- alias: 'Open Purifying air'
  trigger:
    - platform: numeric_state
      entity_id: sensor.moji_weather_air_quality
      above: 100
      for: '00:05:00'

    - platform: numeric_state
      entity_id: sensor.waqi_shanghai_normal_college_primary_division_shanghai
      above: 100
      for: '00:05:00'

    - platform: numeric_state
      entity_id: sensor.living_room_air_quality
      above: 3
      for: '00:05:00'

    - platform: numeric_state
      entity_id: sensor.living_room_dust
      above: 3
      for: '00:05:00'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: fan.living_room
        state: 'off'

      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.living_room_air_quality
            above: 3

          - condition: numeric_state
            entity_id: sensor.living_room_dust
            above: 3

  action:
    - service: notify.notify_to_wechat
      data_template:
        message: >-
          {%- set air_aqi = states('sensor.waqi_shanghai_normal_college_primary_division_shanghai') | int -%}
          室外空气质量：
          {%- if air_aqi <= 50 -%}
          优
          {%- elif air_aqi <= 100 -%}
          良
          {%- elif air_aqi <= 150 -%}
          轻度污染
          {%- elif air_aqi <= 200 -%}
          中度污染
          {%- elif air_aqi <= 300 -%}
          重度污染
          {%- else -%}
          严重污染
          {% endif -%}

          {%- if states('sensor.living_room_air_quality')|int > 3 -%}
            ，室内空气质量：
            {%- if states('sensor.living_room_air_quality') | int <= 5 -%}
            轻度污染
            {%- elif states('sensor.living_room_air_quality') | int <= 8 -%}
            中度污染
            {%- else -%}
            重度污染
            {% endif -%}
            ，即将为你打开空气净化器
            {%- if air_aqi > 100 and is_state('binary_sensor.door_window_sensor_158d00022c5bae', 'on') -%}
            ，请关闭门窗。
            {%- elif air_aqi <= 100 and is_state('binary_sensor.door_window_sensor_158d00022c5bae', 'off') -%}
            ，请打开门窗通风。
            {%- endif -%}
          {%- endif -%}

    # 打开净化器
    - service: fan.turn_on
      data_template:
        entity_id: fan.living_room
        speed: AUTO

    - delay: 00:00:01

    # 摇头
    - service: fan.oscillate
      data_template:
        entity_id: fan.living_room
        oscillating: true


- alias: 'Close Purifying air'
  trigger:
    - platform: numeric_state
      entity_id: sensor.moji_weather_air_quality
      below: 100
      for: '00:05:00'

    - platform: numeric_state
      entity_id: sensor.waqi_shanghai_normal_college_primary_division_shanghai
      below: 100
      for: '00:05:00'

    - platform: numeric_state
      entity_id: sensor.living_room_air_quality
      below: 4
      for: '00:05:00'

    - platform: numeric_state
      entity_id: sensor.living_room_dust
      below: 4
      for: '00:05:00'

  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.living_room_air_quality
        below: 4

      - condition: numeric_state
        entity_id: sensor.living_room_dust
        below: 4


  action:
    - service: notify.notify_to_wechat
      data_template:
        message: >-
          {%- set air_aqi = states('sensor.waqi_shanghai_normal_college_primary_division_shanghai') | int -%}
          室外空气质量：
          {%- if air_aqi <= 50 -%}
          优
          {%- elif air_aqi <= 100 -%}
          良
          {%- elif air_aqi <= 150 -%}
          轻度污染
          {%- elif air_aqi <= 200 -%}
          中度污染
          {%- elif air_aqi <= 300 -%}
          重度污染
          {%- else -%}
          严重污染
          {% endif -%}

          {%- if states('sensor.living_room_air_quality') | int <=3 and states('sensor.living_room_dust') | int <=3 -%}
          ，室内空气质量：优，即将为你关闭空气净化器
            {%- if air_aqi <= 100 and is_state('binary_sensor.door_window_sensor_158d00022c5bae', 'off') -%}
            ，请打开门窗。
            {%- endif -%}
          {% endif -%}

    # 关闭净化器
    - service: fan.turn_off
      data_template:
        entity_id: fan.living_room


